pipeline:
  name: test
  identifier: test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          pwd
                          whoami
                          ls -la 
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        when:
          pipelineStatus: All
        delegateSelectors:
          - test
